### ISSUE TITLE
conan-adapter status and usage questions

### ISSUE THREAD

**Issue by dskvr** [artipie/conan-adapter#14]
1. What is the status of this adapter? Can it be reliably used in testing?
2. ~Usage is unclear and artipie documentation the subject of adding non-default repositories is sparse (or non-existent).~ ~_Additionally, I anticipate this requires building the docker image locally, but `docker build` throws an error related to missing directories, and this too, does not appear to be documented_~

Answered part of this myself, thought unconfirmed as of yet. 
1. Add dependency XML found in `README.md` to the `<dependencies>` member of the `./pom.xml` found in `artipie/artipie` (since there isn't a tag, version is unknown) 
2. Run `mvn package` 
3. Run `docker build .`

**Comment by g4s8** [comment]
I totally agree on this ticket, we need to improve the documentation and provide good decomposition of current work to show the scope. @ChGen please update the README file and edit ticket https://github.com/artipie/conan-adapter/issues/1 to show current work and what was done already.

**Comment by ChGen** [comment]
Current status:
    * Readme file was updated.
    * Conan repo SDK - Java APIs for Conan V2 revisions index support is added.
    * Conan HTTP API - added support for HTTP V1 & V2 API (download & basic search).

**Comment by ChGen** [comment]
Current status:
    Users authentication and permissions support
    Updated conan and dependencies versions
    Published conan-adapter v0.3.0 release.
    README.md was clarified too.
