### ISSUE TITLE
Conan repository SDK

### ISSUE THREAD

**Issue by g4s8** [artipie/conan-adapter#5]
Conan SDK provides methods to generate metadata for Conan repository: it encapsulates `Storage` interface which may contain one or multiple repositories, and exposes a method to generate metadata for a selected repository. Ideally it incrementally updates existing metadata by detecting changes in repository.

The class design may look like:
```
+----------------+
|  class: Conan  |
+----------------+
| repo: Storage  |
+----------------+
| update(Key)    |
+----------------+
```
```java
public final class Conan {
  // repositories storage
  private final Storage storage;

  // + constructor

  // async incremental batch update of repository located at `key` in `storage`
  public CompletionStage<Void> update(Key key) { ... }
```

**Comment by ChGen** [comment]
SDK Status: Implemented RevisionsIndex Java API support.

**Comment by ChGen** [comment]
Status: basic SDK APIs are provided, similar to other artipie adapters.
